### PR TITLE
cache: Attempt to prevent premature destruction of global cache lock

### LINKED ISSUE #531: Segmentation fault when built with mingw-w64
Aspell often crashes with a SEGFAULT when built with mingw-w64, see for example the following reports:
* https://github.com/Alexpux/MINGW-packages/issues/904
* https://bugs.launchpad.net/inkscape/+bug/1412365
* https://bugs.launchpad.net/inkscape/+bug/1714278
* https://sourceforge.net/p/msys2/tickets/180/
* https://sourceforge.net/p/mingw-w64/bugs/432/

This happens since winpthreads was updated in mingw-w64 (the conflicting commits are [[1]](https://sourceforge.net/p/mingw-w64/mingw-w64/ci/1968e60cd5d59727bb325d5b69c8f0d7a2f1fe1b/) and [[2]](https://sourceforge.net/p/mingw-w64/mingw-w64/ci/249898d9ae310959116efa333e4e3e690cf97452/)).

### PR DESCRIPTION
**Pull request by jtanx**
https://stackoverflow.com/questions/335369/finding-c-static-initialization-order-problems#335746

Probably fixes #531 

Previously:
* The destructor for `global_cache_lock` would run before the destructor for GlobalCacheBase (base class for GlobalCache, which is used in various places) - meaning that it was trying to lock/unlock on the already destroyed `global_cache_lock`

### CODE REVIEW

**Comment by Ede123** [comment]
I can confirm that this fixes the issues I described in #531.

File: common/cache-t.hpp [hunk 1]
```diff
@@ -16,6 +16,7 @@ class GlobalCacheBase
   const char * name;
   GlobalCacheBase * next;
   GlobalCacheBase * * prev;
+  static Mutex global_cache_lock;
 protected:
```
Comment (kevina) [inline common/cache-t.hpp]: Please add a comment to why this needs to be in the class.  By following the downstream bug report I was able to make an educated guess, but I want to make the reason to be documented in the code itself.

**Comment by kevina** [comment]
Merged. Sorry for for finding this and sorry for the very long delay.
